return {
PlaceObj('ModItemDecalEntity', {
	'name', "SwissCivilEnsignDecal",
	'entity_name', "SwissCivilEnsignDecal",
	'filename', "H:/Downloads/Games/Surviving Mars/repo/colony_logo_swiss/src/resources/images/png/civil_ensign_1024.png",
}),
PlaceObj('ModItemDecalEntity', {
	'name', "SwissCoatOfArmsDecal",
	'entity_name', "SwissCoatOfArmsDecal",
	'filename', "H:/Downloads/Games/Surviving Mars/repo/colony_logo_swiss/src/resources/images/png/coat_of_arms_1024.png",
}),
PlaceObj('ModItemDecalEntity', {
	'name', "SwissFlagDecal",
	'entity_name', "SwissFlagDecal",
	'filename', "H:/Downloads/Games/Surviving Mars/repo/colony_logo_swiss/src/resources/images/png/flag_1024.png",
}),
PlaceObj('ModItemDecalEntity', {
	'name', "SwissFlagMapDecal",
	'entity_name', "SwissFlagMapDecal",
	'filename', "H:/Downloads/Games/Surviving Mars/repo/colony_logo_swiss/src/resources/images/png/flag-map_1024.png",
}),
PlaceObj('ModItemDecalEntity', {
	'name', "SwissRoundelDecal",
	'entity_name', "SwissRoundelDecal",
	'filename', "D:/downloads/games/Surviving Mars/repo/surviving_mars-colony_logo_swiss/src/resources/images/png/roundel_1024.png",
}),
PlaceObj('ModItemDecalEntity', {
	'name', "SwissSpaceCenterDecal",
	'entity_name', "SwissSpaceCenterDecal",
	'filename', "H:/Downloads/Games/Surviving Mars/repo/colony_logo_swiss/src/resources/images/png/swiss_space_center_black_font_1024.png",
}),
PlaceObj('ModItemMissionLogoPreset', {
	decal_entity = "SwissCivilEnsignDecal",
	display_name = T(781196018151, --[[ModItemMissionLogoPreset SwissCivilEnsign display_name]] "Swiss Civil Ensign"),
	entity_name = "SwissCivilEnsignDecal",
	filter = function (self) return true end,
	group = "Default",
	id = "SwissCivilEnsign",
	image = "UI/civil_ensign.tga",
}),
PlaceObj('ModItemMissionLogoPreset', {
	decal_entity = "SwissFlagMapDecal",
	display_name = T(980265110780, --[[ModItemMissionLogoPreset SwissFlagMap display_name]] "Swiss Flag-Map"),
	entity_name = "SwissFlagMapDecal",
	filter = function (self) return true end,
	group = "Default",
	id = "SwissFlagMap",
	image = "UI/flag-map.tga",
}),
PlaceObj('ModItemMissionLogoPreset', {
	decal_entity = "SwissCoatOfArmsDecal",
	display_name = T(468064439658, --[[ModItemMissionLogoPreset SwissCoatOfArms display_name]] "Swiss Coat of Arms"),
	entity_name = "SwissCoatOfArmsDecal",
	filter = function (self) return true end,
	group = "Default",
	id = "SwissCoatOfArms",
	image = "UI/coat_of_arms.tga",
}),
PlaceObj('ModItemMissionLogoPreset', {
	decal_entity = "SwissFlagDecal",
	display_name = T(584084832579, --[[ModItemMissionLogoPreset SwissFlag display_name]] "Swiss Flag"),
	entity_name = "SwissFlagDecal",
	filter = function (self) return true end,
	group = "Default",
	id = "SwissFlag",
	image = "UI/flag.tga",
}),
PlaceObj('ModItemMissionLogoPreset', {
	decal_entity = "SwissRoundelDecal",
	display_name = T(471181147490, --[[ModItemMissionLogoPreset SwissRoundel display_name]] "Swiss Roundel"),
	entity_name = "SwissRoundelDecal",
	filter = function (self) return true end,
	group = "Default",
	id = "SwissRoundel",
	image = "UI/roundel.tga",
}),
PlaceObj('ModItemMissionLogoPreset', {
	decal_entity = "SwissSpaceCenterDecal",
	display_name = T(233268261125, --[[ModItemMissionLogoPreset SwissSpaceCenter display_name]] "Swiss Space Center"),
	entity_name = "SwissSpaceCenterDecal",
	filter = function (self) return true end,
	group = "Default",
	id = "SwissSpaceCenter",
	image = "UI/swiss_space_center_white_font.tga",
}),
}
